### ISSUE TITLE
Figure out if !oracle exception handler works

### ISSUE THREAD

**Issue by plusreed** [CapofWeird/Rat-Bot#11]
Mentioned this in chat, but I'm not entirely sure this works:
https://github.com/CapofWeird/Rat-Bot/blob/ada4290849220c958ba7db7fa99b9a977cbbbb8e/rat_bot.py#L82-L87

(I'm specifically referring to the syntax where the strings aren't concatenated and are separate arguments)

It might (and I mentioned this in my review of #10) but it's hard to tell by just looking at the code. Just having this here as a reminder to actually check and make sure it works. /cc @CapofWeird

**Comment by CapofWeird** [comment]
Just ran a test, the string concatenation here actually just works seamlessly. Additionally, the `admin_id` variable itself will ping properly; the additional <@> just get printed around the mention!
